export const cryptocurrencies = [
  { name: "Bitcoin", binanceSymbol: "BTC", cryptoSymbol: "btc" },
  { name: "Ethereum", binanceSymbol: "ETH", cryptoSymbol: "eth" },
  { name: "XRP", binanceSymbol: "XRP", cryptoSymbol: "xrp" },
  { name: "Cardano", binanceSymbol: "ADA", cryptoSymbol: "ada" },
  { name: "Dogecoin", binanceSymbol: "DOGE", cryptoSymbol: "doge" },
  { name: "Solana", binanceSymbol: "SOL", cryptoSymbol: "sol" },
  { name: "Polygon", binanceSymbol: "MATIC", cryptoSymbol: "matic" },
  { name: "Litecoin", binanceSymbol: "LTC", cryptoSymbol: "ltc" },
  { name: "Polkadot", binanceSymbol: "DOT", cryptoSymbol: "dot" },
  { name: "Binance USD", binanceSymbol: "BUSD", cryptoSymbol: "busd" },
  { name: "Avalanche", binanceSymbol: "AVAX", cryptoSymbol: "avax" },
  { name: "Dai", binanceSymbol: "DAI", cryptoSymbol: "dai" },
  { name: "Shiba Inu", binanceSymbol: "SHIB", cryptoSymbol: "shib" },
  { name: "Cosmos", binanceSymbol: "ATOM", cryptoSymbol: "atom" },
  { name: "Chainlink", binanceSymbol: "LINK", cryptoSymbol: "link" },
  { name: "Uniswap", binanceSymbol: "UNI", cryptoSymbol: "uni" },
  { name: "Ethereum Classic", binanceSymbol: "ETC", cryptoSymbol: "etc" },
  { name: "Stellar", binanceSymbol: "XLM", cryptoSymbol: "xlm" },
  { name: "Bitcoin Cash", binanceSymbol: "BCH", cryptoSymbol: "bch" },
  { name: "Lido DAO Token", binanceSymbol: "LDO", cryptoSymbol: "ldo" },
  { name: "Internet Computer", binanceSymbol: "ICP", cryptoSymbol: "icp" },
  { name: "Filecoin", binanceSymbol: "FIL", cryptoSymbol: "fil" },
  { name: "Hedera", binanceSymbol: "HBAR", cryptoSymbol: "hbar" },
  { name: "Arbitrum", binanceSymbol: "ARB", cryptoSymbol: "arb" },
  { name: "NEAR Protocol", binanceSymbol: "NEAR", cryptoSymbol: "near" },
  { name: "Quant", binanceSymbol: "QNT", cryptoSymbol: "qnt" },
  { name: "VeChain", binanceSymbol: "VET", cryptoSymbol: "vet" },
  { name: "ApeCoin", binanceSymbol: "APE", cryptoSymbol: "ape" },
  { name: "The Graph", binanceSymbol: "GRT", cryptoSymbol: "grt" },
  { name: "Algorand", binanceSymbol: "ALGO", cryptoSymbol: "algo" },
  { name: "The Sandbox", binanceSymbol: "SAND", cryptoSymbol: "sand" },
  { name: "EOS", binanceSymbol: "EOS", cryptoSymbol: "eos" },
];
